name: 'freebsd-pkg-action'
author: 'Alvin Peters <me@alvinpeters.dev>'
description: 'Build a FreeBSD package'
inputs:
  pkg-name:
    description: 'Name of the package'
    required: true
  prepare-cmds:
    description: 'The CI command to run before building packaging'
    required: false
  build-cmds:
    description: 'The CI command to run after preparation but before packaging'
    required: false
  system-user:
    description: 'System user'
    required: false

outputs:
  file_name:
    description: 'File name of resulting .pkg file.'
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "Hello $INPUT_WHO_TO_GREET."
      shell: sh
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
    - name: Build and package in FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: ${{ inputs.pre-package-cmds }}
        run: |
          ${GITHUB_ACTION_PATH}3_package.sh
    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run goodbye.sh
      run: goodbye.sh
      shell: bash

